### ISSUE TITLE
Recommend using `java_outer_classname` in proto files

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#102]
Reasons:
  * It would make the name obvious. If this option is not given, the Protobuf Compiler would attempt to use the name of the file for the Java class. E.g. for `identifiers.proto` it would be `Identifiers.java`.  But sometime it can be `SomethingOuterClass` when there is a type which conflicts with CamelCase version of the file name.
  * Developers may want to use names like `Identifiers` for utility classes related to the domain.

**Comment by meizabel** [comment]
Closing the issue as its contents has already been merged into a master branch.
