### ISSUE TITLE
Errors in snippets

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/SpineEventEngine.github.io#107]
Currently, the [home page](spine.io) contains several code snippets. There are some ideological errors in those snippets:
 - [x] definition of `Task` aggregate state is not marked with `(entity).kind = AGGREGATE`;
 - [ ] event subscriber methods in `TaskProjection` are not `public`.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, do we want subscriber methods public?

**Comment by alexander-yevsyukov** [comment]
As discussed with @armiol and @dmdashenkov we want subscribing method package-private.
[This issue](https://github.com/SpineEventEngine/core-java/issues/953) is to fix the visibility checking. 

Because of this, the 2nd part of this issue is no longer relevant, and the issue can be closed.
