### ISSUE TITLE
Process Manager concept page links to itself

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#125]
https://spine.io/docs/concepts/process-manager.html

There's no point to linking the page to itself. Please also capitalize “manager”.

**Comment by alexander-yevsyukov** [comment]
Please also replace the text ”Event Handler” with ”Event Subscriber”.

**Comment by meizabel** [comment]
Both issues have been addressed and fixed in #126.

**Comment by alexander-yevsyukov** [comment]
It's closed when it's live.

**Comment by meizabel** [comment]
Closing the issue as it has been resolved.
