### ISSUE TITLE
Guide on creating Rejection messages

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#130]
Rejections are defined differently than regular events. We need to have a dedicated guide for explaining the procedure of defining rejections.

Here are the differences.

1. `java_multiple_files` file option must be set to `false`

Here's why. By setting the value of `java_multiple_files` to `false` to instruct Protobuf Compiler to put all the rejection classes in one outer class.

Then Spine Model Compiler for Java would generate `ThrowableMessage` classes for all
these messages. These classes will be named after the classes of rejection messages.
Putting rejection message classes under an outer class avoids name clash inside the package.

2. Omit `java_outer_classname` option

... so that the outer class name is derived from the name of the file where rejection messages are declared. Usually the outer class names are named using the name with the suffix `Proto`. We want the name to end with `Rejections` so that it's clearly visible what's inside this class.

**Comment by meizabel** [comment]
Closing this issue as Defining Rejections Guide is already live on `spine.io`.
