### ISSUE TITLE
Strange reference in the Command Handler page

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#135]
There's text, which reads:

> For more details, refer to Java section.

“Java” is the link which leads nowhere (to the “Java” page which does not exist). It's not clear why we have this reference at all.

More, the generated events _are_ the state of the application. So preceding wording needs changing too.

**Comment by meizabel** [comment]
Closing the issue as its contents has already been merged into a master branch.
