### ISSUE TITLE
Home page code fragments reference older API

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#140]
- [ ] Use `vBuilder()` instead of `newBuilder()`.
        We encourage people to use our Validating Builder API, which is safer as comparing with the Builder API natively provided by Protobuf.

- [ ] Replace `getBuilder()` with `builder()`.
      We avoid `get` prefix in our API wherever it's possible.

**Comment by meizabel** [comment]
Closing this issue as it is now live on https://spine.io/ Index page.
