### ISSUE TITLE
Update Java Quick Start guide

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#141]
It's needed to import both `time.proto` and `time_options.proto`. The latter is needed for being able to do `(when).in = FUTURE`. It's the recent change.

- [ ] Explain validation options and link to Validation User Guide
Also we need to mention something about the validation options that we add to field declarations. We do not need to give all the details, but explain what we're basically doing here. And then give the link to a user guide on the Validation Library.

- [ ] Use `vBuilder()` API instead of `XxxVBuilder.newBuilder()`
   This is a recent change that we'd like to promote. The current code is still valid, but it's easier to explain `vBuilder()` vs `newBuilder()` thing.
   It's basically this. `vBuilder()` creates a Validating Builder, which checks the values against the validation options when a message is going to be build. `newBuilder()` creates a standard `Builder` natively provided by Protobuf. It is safer to always use `vBuilder()`, and it does not make much sense to specify validating options, if `vBuilder()` is not used. For example,  commands are always validated upon arrival to the server side. But it's too late. It's better to create a valid command on the client side.

- [ ] Fix the code alignment in `requestFactory.command().create()` call
   It should be either aligned by dots, or be on the same line. 

- [ ] Make the code indentation in the code fragments consistent. At the moment `AssignDueDate` has no indentation at all, other messages have their content indented with just a single space character. The indentation should be two spaces.

- [ ] Numeration of the points in "What’s Next" section is broken. We have two ones there.

**Comment by meizabel** [comment]
@armiol I'm assigning it to @JuliaEvseeva to items numbering fix. At  the moment it's spine.io css limitations.

**Comment by armiol** [comment]
@meizabel it's not a CSS limitation.

**Comment by armiol** [comment]
@meizabel please see [this branch](https://github.com/SpineEventEngine/SpineEventEngine.github.io/tree/fix-whats-new-item-numbering) (there's just a single commit on top of `master`) and let me know if this works for you.

**Comment by JuliaEvseeva** [comment]
@armiol, unfortunately this is a markdown limitation. We cannot put `<p>` tag inside the markdown list. To fix this we should use HTML `<ol><li></li></ol>` tags.

**Comment by meizabel** [comment]
@armiol 
LGTM 
Thanks for your support!

**Comment by meizabel** [comment]
Closing this issue. 
All requited changes have been implemented and merged into a master.
