### ISSUE TITLE
Recommend avoiding `_id` suffix in proto fields

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#268]
It polluted the generated code. We know they are IDs by the type. The only place it’s relevant is the first field of an entity state.

**Comment by alexander-yevsyukov** [comment]
It might make sense in a creation command too. But the rest should be entity type nouns.

**Comment by yuri-sergiichuk** [comment]
Closed via #318.
