### ISSUE TITLE
Add `browserconfig.xml` file

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#333]
See [why we need it](https://danaleegibson.com/what-is-the-browserconfig-dot-xml/). Have a look at JxBrowser Support site code as an example.

**Comment by oleksandra-kovalenko** [comment]
We store a [`browserconfig.xml`](https://github.com/SpineEventEngine/SpineEventEngine.github.io/blob/master/favicons/browserconfig.xml) file in the [`favicons` folder](https://github.com/SpineEventEngine/SpineEventEngine.github.io/tree/master/favicons).

**Comment by JuliaEvseeva** [comment]
I have moved the `browserconfig.xml` file to the `root` folder to be consistent with the general rules.
Done with #336.
