### ISSUE TITLE
Add `manifest.json`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#334]
See how JxBrowser Support site does that.

**Comment by oleksandra-kovalenko** [comment]
We store this type of file as [`site.webmanifest`](https://github.com/SpineEventEngine/SpineEventEngine.github.io/blob/master/favicons/site.webmanifest) in the [`favicons` folder](https://github.com/SpineEventEngine/SpineEventEngine.github.io/tree/master/favicons).

**Comment by JuliaEvseeva** [comment]
I have moved the `site.webmanifest` file to the `root` folder to be consistent with the general rules.
Done with #336.
