### ISSUE TITLE
Make text blocks wider

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#433]
Our code conventions allow for 100 columns in a source code line. We should not go to _that_ length in our code examples, but the “window” for code content we have now at the site is too narrow.

First of all, the central content block of the documentation section already limits us in terms of width. In addition to this, we have margins around the code blocks _and_ margins inside the code blocks. As the result, when we need to show more or less wide source code, we have to figure out custom code wrapping tricks.

There's a relatively simple solution to make the code blocks wider. See how Protobuf documentation [does it](https://developers.google.com/protocol-buffers/docs/reference/javascript-generated). The code blocks occupy the whole width of the content panel. The source code indented as the main text, which makes it easier to read.

In addition, this layout give some space at the top right corner or the block so that switching between programming languages (e.g. Java and Kotlin) can be one “in-place”.

**Comment by JuliaEvseeva** [comment]
Did I understand correctly that we want to put tabs inside code blocks at the top right corner?

<img width="1327" alt="Screenshot 2022-01-17 at 19 24 41" src="https://user-images.githubusercontent.com/22611365/149902937-10d2d243-62f8-4554-a00a-6dd11202ff54.png">

**Comment by alexander-yevsyukov** [comment]
Let's have tabs at the left, similarly to how Gradle does. But, maybe, without icons for the languages. And, let's have switching of color schemes at the right corner. I'm not sure if we need to have a copy action. I just added to the mockup, copying from Protobuf site, to see if it would look OK. Have a look...

![image](https://user-images.githubusercontent.com/3116444/149941417-fedaf2bb-ba16-4a64-bb62-1d649e059a32.png)

**Comment by alexander-yevsyukov** [comment]
I guess we can use Material tabs here, having Java as the first tab (instead of Groovy in the mockup above).

**Comment by alexander-yevsyukov** [comment]
See how Protobuf shows their code: https://developers.google.com/protocol-buffers/docs/reference/javascript-generated

**Comment by alexander-yevsyukov** [comment]
Gradle's code examples: https://docs.gradle.org/current/userguide/build_environment.html

**Comment by alexander-yevsyukov** [comment]
Here's how Micronaut does source code tabs: https://docs.micronaut.io/latest/guide/#factories

They also switch the color theme for the whole site, not only for the source code. We may want it later, but certainly not now.

**Comment by alexander-yevsyukov** [comment]
The 2nd option looks better for me too.

**Comment by JuliaEvseeva** [comment]
> Can we make the color switching icon _float_ there so that it takes the space of the last line of the text paragraph before the code block?

Yes, I will try it.

And if we will have a new icon near the code block, should I hide our global switcher?
<img src="https://user-images.githubusercontent.com/22611365/150090936-e2617272-fa0b-44fe-85cb-b880c2bdb4bd.png" width="180"/>

**Comment by alexander-yevsyukov** [comment]
Yes. Let's have only those near code blocks. And each of them is global.
