### ISSUE TITLE
Give credits to OOS

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#67]
Now the section “Software that help us build Spine” mentions only CloudRepo.
We need to list open-source software libraries and tools that we use.
Let's have a popup window which lists these tools with links to corresponding project sites and licenses.

**Comment by meizabel** [comment]
Can anyone give me a hand in listing all required technologies/libraries and tools used? 
I would really appreciate it and add tools names with links on the Spine About page.

**Comment by alexander-yevsyukov** [comment]
It's mostly here: 

https://github.com/SpineEventEngine/config/blob/master/gradle/dependencies.gradle

For Google Cloud dependencies, please see Gradle files in the corresponding repository.

**Comment by alexander-yevsyukov** [comment]
We also want to automate gathering this info. See [this issue](https://github.com/SpineEventEngine/config/issues/37).

**Comment by armiol** [comment]
@JuliaEvseeva here is the fragment of the script, which loads the markdown dynamically:
```javascript
<button id="load-markdown-btn" 
        repo="https://raw.githubusercontent.com/SpineEventEngine/core-java"
        loaded="false">
            Load Markdown
</button>
<div id="md-destination"></div>

<script src="https://cdn.rawgit.com/showdownjs/showdown/1.9.0/dist/showdown.min.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    var converter = new showdown.Converter();
    const loadedAttr = "loaded";
    const repoAttr = "repo";
    $("#load-markdown-btn").click(function() {
        var clickedElement = $(this);
        var loaded = clickedElement.attr(loadedAttr);
        if(loaded === "false") {
            var repositoryUrl = clickedElement.attr(repoAttr);
            $.get(
                repositoryUrl + "/master/license-report.md",
                function(data) {
                    var html = converter.makeHtml(data);
                    $("#md-destination").html(html);
                    clickedElement.attr(loadedAttr, "true");
                }
            );
        }
    });
</script>

```
