### ISSUE TITLE
Rework sub-header text in About Spine

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#68]
It's way too long. Consolidate the message making the focus on reactive DDD rather than implementation things like Protobuf and gRPC.

**Comment by meizabel** [comment]
I propose the following statement/message: 

Spine Event Engine is a framework for building cloud applications and transforming EventStorming into a working domain model code.

I look forward to your comments.

**Comment by alexander-yevsyukov** [comment]
Please link this issue to a PR.

**Comment by alexander-yevsyukov** [comment]
This is going to be addressed in #118.

**Comment by meizabel** [comment]
Closing this one as it has been addressed in #118
