### ISSUE TITLE
Add Validation and Multi-tenancy to Features

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#78]
- [x] *Validation Library and Proto Options*
        It's library in the sense that you can not use it at all in the framework. But when you do, it's easier and safer.

- [x] *Built-in Multi-tenancy Support*
     You don't have to add `tenantId` parameter all over the application if you want to make your app serve more than one company. With few simple steps (link) your app becomes multi-tenant.

- [ ] Rework *Scale with micro-services*
     We don't want to recommend scaling read and write side separately, as the remoting costs between the sides may be significant.
- [ ] *Multi-language library for date/time types*
     Types that look familiar, conversion to/from Java 8 Date/Time. Compatible with client frameworks for other languages (link).

**Comment by meizabel** [comment]
At the moment https://spine.io/about/ features description page has Built-in Multitenancy support and Built-in Validation features description. 

Should we add descriptions of Multi-language library for date/time types and Scaling with micro-services too? Is this content request still valid?

**Comment by alexander-yevsyukov** [comment]
No. Let's not do it now. The word “microservices” would bring more confusion.
