### ISSUE TITLE
Defining Aggregate guide

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#82]
The guide should provide steps for creating a new aggregate.

Put a link to this document from the “Entity States” section of the “Naming Conventions” document. There is a piece which tells about using a word `Aggregate` in a class name. A user may be interested in learning more about defining an aggregate when reading about naming conventions.

**Comment by meizabel** [comment]
Could you please clarify if we still need it and it's our priority for the release. 
If yes, let's include it into our documentation development roadmap.

**Comment by meizabel** [comment]
Closing the issue as its contents has already been merged into a master branch.
