### ISSUE TITLE
Suggested wording for explaining rejections

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#84]
Consider this text:

A rejection is a special “negative” kind of events. If an event is a fact of something happened to a domain model, a rejection is a fact that states the reason _why_ a command was not handled.

**Comment by meizabel** [comment]
I propose the following in the current version of Basic Concepts section: 

Rejection is a state of business logic which can be handled by the end user. It's a special “negative” kind of events. 

In Spine, rejections are defined as Protobuf messages. If an event is a fact of something that happened to a domain model, a rejection is a fact that states the reason why a command was not handled. 

Consider the following examples of rejections: 
- `CreditCardValidationDecllined`, 
- `OrderCannotBeEmpty`, 
- `InsufficientFunds`.

**Comment by alexander-yevsyukov** [comment]
@meizabel, looks good. Please apply.

**Comment by meizabel** [comment]
Propose to close the issue as the content is already on the website Rejection concept page https://spine.io/docs/concepts/rejection.html
The issue was addressed within the framework on redesigning the whole Concepts section.
