### ISSUE TITLE
Add README.md for `core-java/client` module and `web`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/SpineEventEngine.github.io#97]
The About page references the [client](https://github.com/SpineEventEngine/core-java/tree/master/client) module of `core-java`, and `web` repository as a JavaScript client. 

It would be good to have a short readme text that would give instructions as to adding the client library to a project.

**Comment by meizabel** [comment]
Is this issue still up-to-date? 
If yes and it's our priority for this release, let's plan to include it to our documentation development roadmap.

**Comment by alexander-yevsyukov** [comment]
Closed in favour of #378.
